import Head from 'next/head'
import { useState, useEffect } from 'react'
import Image from 'next/image'

export default function BackOrClose() {
  const closeWebViewJSI = (e) => {
    if(!!window.native) {
      window.native.closeWebView()
    }
  }

  const backOrClose = (e) => {
    if(!!window.native) {
      window.native.backOrClose()
    }
  }
  
  var myHistory = [];
  const [historyBackCount, setHistoryBackCount] = useState(-1)
  const emptyStack = () => {
    // window.history.state = null;
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
  }
  const customHistoryBack = (e) => {
    history.go(historyBackCount)
  }


  const oneminushistory = () => {
    history.go(1 - history.length);
  }

  const jsihistory = () => {
    if(!!window.native) {
      window.native.backOrClose()
    }
    history.back()
  }

  const historyjsi = () => {
    history.back()
    if(!!window.native) {
      window.native.backOrClose()
    }
  }
  

  const closeWebViewHistoryBack = (e) => {
    history.back()
  }

  return (
    <div>
      <Head>
        <title>Back Or Close</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container p-8 bg-slate-100'>
      <a href='https://webviews-psi.vercel.app/ramankit4' className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
              Ramankit 3 for case 3
          </a>
      </div>
    </div>
  )
}
