import Head from 'next/head'
import { useState, useEffect } from 'react'
import Image from 'next/image'

export default function BackOrClose() {
  const closeWebViewJSI = (e) => {
    if(!!window.native) {
      window.native.closeWebView()
    }
  }

  const backOrClose = (e) => {
    if(!!window.native) {
      window.native.backOrClose()
    }
  }
  
  var myHistory = [];
  const [historyBackCount, setHistoryBackCount] = useState(-1)
  const emptyStack = () => {
    // window.history.state = null;
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
  }
  

  const oneminushistory = () => {
    history.go(1 - history.length);
  }

  const recursivehistoryback = () => {
    while(history.length > 0) {
      console.log(history.length);
      history.go(-1);
    }
  }

  const jsihistory = () => {
    if(!!window.native) {
      window.native.backOrClose()
    }
    history.back()
  }

  const historyjsi = () => {
    history.back()
    if(!!window.native) {
      window.native.backOrClose()
    }
  }
  

  const closeWebViewHistoryBack = (e) => {
    history.back()
  }

  return (
    <div>
      <Head>
        <title>Back Or Close</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container p-8 bg-slate-100'>
        <div className="text-3xl font-bold pb-4 items-center">
          Back Or Close
        </div>

        <div className="grid grid-cols-1 gap-2">
          <button onClick={backOrClose} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Back Or Close
          </button>
          <button onClick={closeWebViewJSI} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Close WebView (JSI)
          </button>
          <button onClick={closeWebViewHistoryBack} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Close WebView (history.back)
          </button>
          <button onClick={emptyStack} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
            Empty stack - hack hai abhi
          </button>
          <a href='https://www.tiket.com' className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">Navigate directly</a>
          <button onClick={jsihistory} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
              JSI back + history.back
          </button>
          <button onClick={historyjsi} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
              history.back + JSI back
          </button>
          <button onClick={oneminushistory} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
              1 - JSI back
          </button>
          <div className="shadow-md rounded-md p-2 w-full bg-neutral-50 text-center">
            <input value={historyBackCount} onChange={ e => setHistoryBackCount(e.target.value) } className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mb-2" type="number"/>
            <button onClick={customHistoryBack} className="shadow-md rounded-md p-2 w-full bg-blue-500 active:bg-sky-600 text-white text-center">
              History Back
            </button>
          </div>
          <div className="shadow-md rounded-md p-2 w-full bg-neutral-50 text-center">
            <a href='https://www.blibli.com/home/favourites' className="shadow-md rounded-md p-2 w-full bg-blue-500 active:bg-sky-600 text-white text-center">
              blibli
            </a>
          </div>
          
        </div>
      </div>
    </div>
  )
}
