import Head from 'next/head'
import { useState, useEffect } from 'react'
import Image from 'next/image'

export default function BackOrClose() {
  const closeWebViewJSI = (e) => {
    if(!!window.native) {
      window.native.closeWebView()
    }
  }

  const backOrClose = (e) => {
    if(!!window.native) {
      window.native.backOrClose()
    }
  }
  
  var myHistory = [];
  const [historyBackCount, setHistoryBackCount] = useState(-1)
  const emptyStack = () => {
    // window.history.state = null;
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
    window.history.pushState(myHistory, "ramankit", "ramankit");
  }
  const customHistoryBack = (e) => {
    history.go(historyBackCount)
  }


  const oneminushistory = () => {
    history.go(1 - history.length);
  }

  const jsihistory = () => {
    if(!!window.native) {
      window.native.backOrClose()
    }
    history.back()
  }

  const historyjsi = () => {
    history.back()
    if(!!window.native) {
      window.native.backOrClose()
    }
  }
  

  const closeWebViewHistoryBack = (e) => {
    history.back()
  }

  const removeHashAndGotoB = (e) => {
    history.back();
    window.location.href= 'https://www.tiket.com';
  }


  return (
    <div>
      <Head>
        <title>Back Or Close</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container p-8 bg-slate-100'>
        <div className="text-3xl font-bold pb-4 items-center">
          Back Or Close
        </div>

        <div className="grid grid-cols-1 gap-2">
          <a href='https://webviews-psi.vercel.app/ramankit' className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
              Ramankit 4 for case 3
          </a>
          </div>
          <div className="grid grid-cols-1 gap-2">
          <a href='https://webviews-psi.vercel.app/ramankit4#1234' className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
Add Hash tag          </a>
          </div>
          <div className="grid grid-cols-1 gap-2">
          <a onClick={removeHashAndGotoB} className="shadow-md rounded-md p-2 w-full bg-neutral-50 active:bg-sky-300 text-center">
             Remove Hash from history and go to next page
          </a>
          </div>
          <img src='vipul.com/abcd'></img>
      </div>
    </div>
  )
}
